//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCBooking
{


    public partial class AdminDashboard
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        protected global::System.Web.UI.ScriptManager ScriptManager1;

        /// <summary>
        /// lblVCTypeFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblVCTypeFilter;

        /// <summary>
        /// ddlVCTypeFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlVCTypeFilter;

        /// <summary>
        /// litMeetingFilterSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMeetingFilterSummary;

        /// <summary>
        /// gvMeetings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvMeetings;

        /// <summary>
        /// hfDetailsVCId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfDetailsVCId;

        /// <summary>
        /// btnLoadDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLoadDetails;

        protected global::System.Web.UI.WebControls.Literal litDetailTitle;
        protected global::System.Web.UI.WebControls.Panel pnlDetailsEmpty;
        protected global::System.Web.UI.WebControls.Panel pnlDetailsContent;
        protected global::System.Web.UI.WebControls.Literal litDetailVCId;
        protected global::System.Web.UI.WebControls.Literal litDetailStatus;
        protected global::System.Web.UI.WebControls.Literal litDetailCompany;
        protected global::System.Web.UI.WebControls.Literal litDetailPlatform;
        protected global::System.Web.UI.WebControls.Literal litDetailAccount;
        protected global::System.Web.UI.WebControls.Literal litDetailLocation;
        protected global::System.Web.UI.WebControls.Literal litDetailDate;
        protected global::System.Web.UI.WebControls.Literal litDetailTime;
        protected global::System.Web.UI.WebControls.Literal litDetailCreatedBy;
        protected global::System.Web.UI.WebControls.Literal litDetailCreatedDate;
        protected global::System.Web.UI.WebControls.Literal litDetailParticipantCount;
        protected global::System.Web.UI.WebControls.Literal litDetailApiStatus;
        protected global::System.Web.UI.WebControls.Literal litDetailUnitFloor;
        protected global::System.Web.UI.WebControls.Literal litDetailVCDetails;
        protected global::System.Web.UI.WebControls.Literal litDetailMeetingId;
        protected global::System.Web.UI.WebControls.Literal litDetailPassword;
        protected global::System.Web.UI.WebControls.HyperLink lnkDetailJoinUrl;
        protected global::System.Web.UI.WebControls.Literal litDetailParticipants;
        protected global::System.Web.UI.WebControls.Literal litDetailCancellation;
        protected global::System.Web.UI.WebControls.Button btnDetailsReschedule;
        protected global::System.Web.UI.WebControls.Button btnDetailsCancel;
        protected global::System.Web.UI.WebControls.Button btnDetailsDelete;


        /// <summary>
        /// hfCancelVCId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfCancelVCId;

        /// <summary>
        /// txtCancelReason control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtCancelReason;

        /// <summary>
        /// btnConfirmCancel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmCancel;


        /// <summary>
        /// hfRescheduleVCId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfRescheduleVCId;

        /// <summary>
        /// txtNewDate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNewDate;

        /// <summary>
        /// txtNewFromTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNewFromTime;

        /// <summary>
        /// txtNewToTime control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtNewToTime;

        /// <summary>
        /// txtRescheduleReason control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtRescheduleReason;

        /// <summary>
        /// btnConfirmReschedule control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmReschedule;


        /// <summary>
        /// hfDeleteVCId control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteVCId;

        /// <summary>
        /// btnConfirmDelete control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnConfirmDelete;    }
}
